# =========================================================
#   WHAT I DO
# =========================================================

[ whatido ]
heading = "What I do."
id      = "what-i-do"
copy = """
I am a freelance web developer, and my main interest is in working towards a 
more ethical web. You can read more about the [ethical web](#ethical-web) 
below.

In my work, I prioritize accessibility for all users, performance, speed, and 
following best practices and standards.

I am available for hire for any of the following:

- [building new websites from scratch](/services/new-website/)
- [fixing issues on existing websites](/services/fix-issues-on-an-existing-website/)
- [performance and accessibility consulting](/services/website-audit/)

For more information, see the [services](/services/) page.
"""



# =========================================================
#   TESTIMONIALS
# =========================================================

[[ whatido.testimonials ]]
author = "Jan T."
site   = "https://thisblogisaboutyou.com"
image  = "https://dl.dropboxusercontent.com/s/pw1k830qtj7twdf/jan.jpg?dl=0"
copy   = """ \
It's so easy for me to add content to my blog! I didn't have a clear idea of \
how I wanted it to look, but Bradley managed to take my few ideas and make it \
look really great. He also added new features I needed in record time. \
"""


[[ whatido.testimonials ]]
author = "Kerri S."
site   = "https://brakdakkie.co.za"
image  = "https://dl.dropboxusercontent.com/s/zuh3j8aa5k7pzi4/kerri.jpg?dl=0"
copy   = """ \
All through the process Bradley amazed me. I'm so happy with how the redesigned \
site turned out. He is also so responsive and so quick to make changes. I \
couldn't be happier.
"""



# =========================================================
#   PORTFOLIO
# =========================================================

[ portfolio ]
heading = "Portfolio."
id      = "portfolio"

[[ portfolio.items ]]
title       = "This Blog Is About You"
url         = "https://thisblogisaboutyou.com"
description = "Personal blog"
image       = "screenshots/this-blog-is-about-you.png"
stack       = ["html", "sass", "eleventy"]
[[ portfolio.items.copySections ]]
heading = "Project story"
copy = """
In early 2021, Jan was looking to start a blog. She approached me, not really
knowing much of what she wanted. As I normally do, I asked her to send me some
links to sites that she liked. Based on what she sent me, I could tell she was
looking for something clean and minimal. And that's what I think I delivered!
I did have some fun with the fancy dot that's on the front page and the header.
"""
[[ portfolio.items.copySections ]]
heading = "Tech decisions"
copy = """
I was working with Next.js a lot at this point, but I felt that it was a little
much for a _completely_ static blog. Jan needed to be able to add content, of
course, but there was no actual dynamic content — only the blog posts that she
was writing.

This was the project that got me exploring static site generators more
seriously, and I eventually found — and fell in love with —
[Eleventy](https://11ty.dev). It is a such a joy to work with. I had already
completed the project using Next, but I decided to redo it with Eleventy. I'm so
glad I did, because 11ty has become my goto for static sites.

The frontend is hosted on Netlify, and the CMS is GraphCMS (now Hygraph). The
frontend stack is pure HTML, vanilla Javascript and Sass — no libraries
whatsoever.

I also wrote a custom plugin so that Jan could write captions for the images,
and they would be semantically correct for screen readers etc. — but also
styled nicely.
"""
[[ portfolio.items.links ]]
type = "primary"
text = "visit live site"
url  = "https://thisblogisaboutyou.com"
[[ portfolio.items.links ]]
type = "secondary"
text = "see on github"
url  = "https://github.com/bradleyburgess/jan-blog_11ty"


[[ portfolio.items ]]
title       = "Brakdakkie Guest Cottages"
url         = "https://brakdakkie.co.za"
description = "Bed & Breakfast"
image       = "screenshots/brakdakkie.png"
stack       = ["html", "sass", "javascript", "eleventy"]
[[ portfolio.items.copySections ]]
heading = "Project story"
copy = """
Brakdakkie Guest Cottages is one of the absolute highlights of Prince Albert,
located in the Karoo, Western Cape, South Africa. It aims to be an authentically
Karoo accommodation experience, taking you back to a simpler time. The décor is
elegant and tasteful, featuring trinkets and furnishing reminiscent of a time
gone by.

As incredible a destination it is, their website was in need of an update.
Kerri trusted me to take the spirit of Brakdakkie and create a design that
matched its tasteful but rustic spirit. I took the existing content and
reorganized the site map and layout to better showcase the cottages.
"""
[[ portfolio.items.copySections ]]
heading = "Tech decisions"
copy = """
Like Jan's blog and this wite, I decided to go with [Eleventy](https://11ty.dev)
to build a purely static site. The frontend stack is vanilla Javascript, relying
on only one third-party library — [Photoswipe](https://photoswipe.com). I did
borrow / adapt one Web Component / Custom Element for the accordion component
on the about page (Policies).

The frontend is hosted on Netlify, and for the CMS I chose GraphCMS (now 
Hygraph).
"""
[[ portfolio.items.links ]]
type = "primary"
text = "visit live site"
url  = "https://brakdakkie.co.za"
[[ portfolio.items.links ]]
type = "secondary"
text = "see on github"
url  = "https://github.com/bradleyburgess/brakdakkie_11ty"


[[ portfolio.items ]]
title       = "Bradley Burgess"
url         = "https://bradley-burgess.com"
description = "Personal website"
image       = "screenshots/bradley-burgess.png"
stack = ["html", "sass", "javascript", "eleventy", "node", "docker", "postgres", "python"]
[[ portfolio.items.copySections ]]
heading = "Project story"
copy = """
I've always loved the internet. I can remember the moment I fell in love with
it — watching the scene in the original Mission Impossible movie when Ethan
Hunt (Tom Cruise) is sending an email to Max (Vanessa Redgrave) in his hotel
room.

Since then I've always tinkered with web technologies, and my personal site has
taken many forms over the years. But I am most happy with this iteration. I
wanted to create an online home that represents all my interests — as a
musician, web developer, tinkerer, etc. — where people can come to find music
but also learn about my web development journey, and where folks interested in
my dev projects could hear a little Bach as well.

I wanted a clean, modern, sophisticated design, but that is also inviting.
The emphasis is on the content, which is also why I've spent a good deal of
time making sure the performance is lightning fast.

I also wanted to have everything in one place. I was using Gumroad to sell
some scores, but I wanted the new site to have everything right there.
"""
[[ portfolio.items.copySections ]]
heading = "Tech decisions"
copy = """
I spent a long time weighing different options, and I ended up going with a
static frontend built with [Eleventy](https://11ty.dev). I wanted to use as
little Javascript as possible, as to make it perform well under any condition.

The real challenge was the shop. It definitely would have been easier to go
all-in Javascript with something like Next.js, and perhaps that would have been
a better choice. But I also realized that — realistically — the e-commerce part
of the site wasn't the main focus. I managed to get the shop working
fully-featured without relying on Javascript at all for the "Buy Now" links —
the only caveat being that you need Javascript for using the cart functionality.

I also create some Web Components / Custom Elements for the media players on the
[music page](/music/#video). They are progressively enhanced, and allow for the
playlist functionality. Without Javascript, they operate as regular hyperlinks.

The backend is a Node.js / Express server that's managed in Docker containers. I
produce all the scores with Lilypond. I wrote an internal Python CLI to generate
the pdfs programatically, create the sample images (with "sample copy"
watermark), upload them to my self-hosted S3 storage, and sync with the Stripe
API. 

After a successful purchase, the scores are watermarked with the buyer's
information for licensing, before being uploaded to my S3 storage. Presigned
urls are then generated and sent with SendGrid. I use PostgreSQL to maintain my
own records of purchases and also to log submissions from the contact page form
— just in case something goes wrong with the transactional emails.
"""
[[ portfolio.items.links ]]
type = "primary"
text = "see on github"
url  = "https://github.com/bradleyburgess/bradley-burgess.com_11ty"




# =========================================================
#   ETHICAL WEB
# =========================================================

[ ethicalweb ]
heading = "Ethical web."
id      = "ethical-web"

copy = """
As a web developer, my main interest is in helping to create a more ethical 
web. What do I mean by the “ethical web”? There is no single, universally 
agreed-upon definition, but In short, the ethical web puts the user and the 
environment first.

I do my best to only use open-source tools, and I try to only choose products
and services from companies with good, (more) ethical business practices,
especially those with a stated green policy. I have switched providers when I
don't feel that a company's values align with my own ([here's one
example](https://www.nocloudflare.com/)), and do reassess platforms, tools and
services from time to time.


Ethically-designed websites:

- are accessible to any user, regardless of (dis)ability
- are secure, and transparent about privacy
- are lightweight and use minimal device resources
- don’t make many assumptions about the user
- cater to a wide range of devices and internet speeds
- are eco-concious, choosing environmentally-friendly tools and green web 
  hosting

A great reference is the 
[“Ethical Web Principles” document](https://www.w3.org/2001/tag/doc/ethical-web-principles/) 
created by the World Wide Web Consortium (W3C), which outlines some of these 
requirements. [The Green Web Foundation](https://www.thegreenwebfoundation.org/) 
is a good resource for understanding the need for a fossil-free internet.


In building accessible websites, these are some of the considerations I make:

- is this site 100% functional for persons using screen readers?
- do all images have appropriate “alt” text?
- can this site work well with javascript disabled?
- is the site 100% useable for persons that rely on keyboard-only navigation?
- are animations disabled for users with motion sensitivity?
- do sliders / carousels have easy-to-use controls?
- is there enough color contrast so that text is easily readable?
- does the site still work at high zoom levels?
- does the site perform well on very slow internet speeds?

I am always trying to learn more about best practices for accessible and 
ethical web design and development. You can read more about that tools I use 
below. If you notice anything that needs improvement on this site, 
please [let me know](/contact).
"""



# =========================================================
#   OTHER PROJECTS
# =========================================================

[ otherprojects ]
heading = "Other Projects."
id      = "other-projects"
copy = """
These days, I am primarily making static sites (i.e. not web apps), but I love 
tinkering, and have made various other projects.

I am most at home with Javascript in the browser and Node, but I am pretty 
comfortable with Python and reasonably adept with SQL and Google Sheets as well;
if you need help creating a robust spreadsheet solution to a problem, I am
available for that work as well. See the [services page](/services/#development)
for more info.
"""

[[ otherprojects.items ]]
title       = "hymnary-scrape"
description = "A simple python cli app to download hymn texts from hymnary.org"
stack       = [ "python" ]
github      = "https://github.com/bradleyburgess/hymnary-scrape"
image       = "https://images.unsplash.com/photo-1520446266423-6daca23fe8c7?w=1920"
imageAlt    = ""


[[ otherprojects.items ]]
title       = "docker-dropbox"
description = """Dropbox in Docker. A fork of @janeczku/docker-dropbox, which \
is now unmaintained. Updated for Ubuntu Jammy."""
stack       = [ "docker", "linux" ]
github      = "https://github.com/bradleyburgess/docker-dropbox"
image       = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Antu_dropbox.svg/512px-Antu_dropbox.svg.png"
imageAlt    = ""


[[ otherprojects.items ]]
title       = "eleventy-plugin-broken-links"
description = "A plugin for @11ty/eleventy to check your build for broken links."
stack       = [ "node", "eleventy" ]
github      = "https://github.com/bradleyburgess/eleventy-plugin-broken-links"
image       = "https://live.staticflickr.com/1640/24445486463_a3c6298ed0_b.jpg"
imageAlt    = ""


[[ otherprojects.items ]]
title       = "256-color-matcher"
description = "A web app to find the closest matching standard 8-bit / 256 color from a given input."
stack       = [ "javascript", "html", "css" ]
github      = "https://github.com/bradleyburgess/256-color-matcher"
external    = "https://256-color-matcher.netlify.app"
image       = "projects/256-color-matcher.png"
imageAlt    = ""



# =========================================================
#   MY TOOLS
# =========================================================

[ mytools ]
heading = "My tools."
id      = "my-tools"
copy    = """
Here are some of the tools I use in my work as a developer and musician.
"""

# development tools ---------------------------------------
[ mytools.development ]
heading = "Development tools."

    [[ mytools.development.tools ]]
    title       = "Pop!_OS"
    class       = "popos"
    description = "linux distribution"

    [[ mytools.development.tools ]]
    title       = "Figma"
    class       = "figma"
    description = "design & prototype"

    [[ mytools.development.tools ]]
    title       = "VS Code"
    class       = "vscode"
    description = "code editor"

    [[ mytools.development.tools ]]
    title       = "NeoVim"
    class       = "neovim"
    description = "code editor"

    [[ mytools.development.tools ]]
    title       = "Eleventy"
    class       = "eleventy"
    description = "static site generator"

    [[ mytools.development.tools ]]
    title       = "Netlify"
    class       = "netlify"
    description = "hosting & deployment"

    [[ mytools.development.tools ]]
    title       = "Digital Ocean"
    class       = "digitalocean"
    description = "hosting & deployment"

    [[ mytools.development.tools ]]
    title       = "Hygraph"
    class       = "hygraph"
    description = "content management system"

    [[ mytools.development.tools ]]
    title       = "Strapi"
    class       = "strapi"
    description = "content management system"

# languages -----------------------------------------------
[ mytools.languages ]
heading = "Languages & Frameworks."

    [[ mytools.languages.tools ]]
    title = "HTML"
    class = "html"

    [[ mytools.languages.tools ]]
    title = "CSS"
    class = "css"

    [[ mytools.languages.tools ]]
    title = "Javascript"
    class = "javascript"

    [[ mytools.languages.tools ]]
    title = "Typescript"
    class = "typescript"

    [[ mytools.languages.tools ]]
    title = "React"
    class = "react"

    [[ mytools.languages.tools ]]
    title = "SASS"
    class = "sass"

    [[ mytools.languages.tools ]]
    title = "Bash"
    class = "bash"

    [[ mytools.languages.tools ]]
    title = "Python"
    class = "python"


# music tools ---------------------------------------------
[ mytools.music ]
heading = "Music tools."

    [[ mytools.music.tools ]]
    title       = "Lilypond"
    class       = "lilypond"
    description = "music notation"

    [[ mytools.music.tools ]]
    title       = "Jitsi Meet"
    class       = "jitsimeet"
    description = "video conferencing for lessons"

    [[ mytools.music.tools ]]
    title       = "Audacity"
    class       = "audacity"
    description = "audio editing"

    [[ mytools.music.tools ]]
    title       = "Shotcut"
    class       = "shotcut"
    description = "video editing"