copy = """

September 12, 2023  
Holy Name of Jesus Cathedral  
Raleigh, NC

## Bach: Sinfonia and Orgelbüchlein

The first half of this program is dedicated to Bach — works by and inspired by
him. We began with Marcel Dupré’s arrangement of the opening movement from J. S.
Bach’s 29th cantata: *Wir danken dir, Gott, wir danken dir* (“We thank you, God, we
thank you”). The cantata was written for the 1731 annual celebration of
inauguration of the new town council in Leipzig. This sinfonia, the opening
movement, is well-known, and is an example of Bach reworking existing music in a
later composition. The existing music is the Prelude from his E Major Violin
Sonata — so in a sense this is a transcription of a transcription! Dupré, who
arranged the Sinfonia, was one of the most formidable and important French
organists of the 20th century, and he brought his ample technique to bear in
creating this transcription.

We’ll now hear three chorale preludes from Bach’s *Orgelbüchlein* — “Little Organ
Book”. “Chorale prelude“ refers to an organ composition based on usually a
Lutheran hymn tune, and most often they are intended to be used during church
services. The title page of this collection by Bach reads: “Little Organ Book,
In which a beginning organist receives given instruction as to performing a
chorale in a multitude of ways while achieving mastery in the study of the
pedal…” As I’ve often found to be the case, Bach had a rather unusual idea of
what beginners are capable of, with the 46 pieces in this collection
encompassing almost every variety of Baroque organ technique.

## Liszt: Prelude & Fugue on BACH

We turn now to Franz Liszt, the great 19th-century virtuoso pianist, visionary
and prolific composer, charismatic conductor, influential teacher, essayist, and
philanthropist. Liszt had many facets to his personality and his music: his
music can be poetic, thrilling, divine, sardonic, regal, and playful — sometimes
all in the same piece. He is most known for his extraordinary piano
compositions: most notably the Sonata, the demanding études, and numerous
transcriptions of operatic works. 

One might wonder how you can have a musical composition based on a name,
especially when the musical alphabet spans A to G, and Bach’s name has an H! In
German, “H” is a B natural, and “B” is a B flat. So Bach’s name is B-flat, A, C,
B-natural.

The B-A-C-H theme was used by Bach himself and other composers after him. In
Liszt’s hands, the chromatic theme can at times seem very menacing, especially
at the opening. However, in the fugue, it sounds almost pleading at times, and
the final pianissimo statement of the theme is almost celestial. Liszt gives the
organist very little in terms of registration — the stops or sounds that the
organist is to use. Whenever I play this piece, I try to explore the full sonic
range of the instrument — from very soft to full organ — and extract as many
interesting colors as I can.

## Langlais and Guilmant

We’ll next hear some music by two French organists. Along with fellow French
organist Louis Vierne, Jean Langlais was one of the most famous blind musicians
of the 20th century. He was a tremendously gifted organist and improviser, and
is especially known for his large body of organ compositions — the complete
recording of which spans 26 CDs. He concertized prolifically, and made a number
of European and American tours. His style was rather individual and eclectic,
and his harmonic language was often more tonal than e.g. Messiaen. There is
often a certain folkiness to his music as well. Compared to some of his
contemporaries and the generation before him, his textures are also somewhat
leaner and cleaner, and this will be very apparent in contrast with the Guilmant
which we’ll hear after. The two Langlais pieces are from a set paying homage to
Frescobaldi, who was a notable Italian virtuoso keyboard player and composer in
the late 16th and early 17th century. 

Alexandre Guilmant was also a notable organist, and possibly as prolific a
composer as Langlais. He held two important positions in Paris. First, he was
organist at Trinity Church, a position later held by Olivier Messiaen — one of
the most important organists composers of the 20th century. In addition, Guilmant
succeeded Widor as the organ professor at the Paris Conservatory. His most
notable student there was none other than Marcel Dupré, whose transcription of
Bach began tonight’s program.

## Interstellar

To close tonight’s program, we’ll hear music from Hans Zimmer’s Academy
Award-nominated score from the 2014 film *Interstellar*. Hans Zimmer has written
the musical score to some of the biggest films of the last 30 years. His immense
discography includes: Black Hawk Down, Madagascar, The Ring, The Prince of
Egypt, Mission: Impossible 2, Gladiator, Pearl Harbor, Hannibal, The Last
Samurai, The Da Vinci Code, Pirates of the Caribbean, Frost/Nixon, Kung Fu
Panda, and many more. He is probably best known for his work with director
Christopher Nolan: the Batman / Dark Knight franchise, Inception, Dunkirk, The
Prestige, and — my favorite — Interstellar. If you haven’t seen the film, it is
a science-fiction adventure on an epic scale. However, the heart of the film is
defined by relationships — especially between Cooper and his daughter Murph. In
the end, we discover that the only two things that can transcend space and time
are gravity and love. 

In an interview, Nolan said that it was important that the music for the film
not pay too close attention to the genre. And so, he gave Zimmer one page from
the script — including some dialogue and some ideas behind the movie but without
any indication as to the genre or the scale of the movie, and told him to see
what he came up with in a day. The dialogue was between a father and son. Zimmer
said that he wrote some ideas based on his experience being a father to a son.
It turned out however that the son was in fact a daughter — Murph, and that the
relationship would span galaxies and decades. However, the material that he came
up with allegedly formed the basis for almost the entire score.

The organ is featured heavily in the score. While it is not a religious film,
there definitely is a sense of religiosity to it. Nolan and Zimmer chose to
include the pipe organ as representative of mankind’s search for the mystical
and metaphysical — what’s beyond us as humans on this earth.

The music for *Stay* is heard right at the beginning of the film, and culminates
with Cooper taking off into space to begin his journey to another galaxy.
*Cornfield Chase* is heard when Cooper and his two children are chasing a drone
they discovered flying above a cornfield. It ends abruptly as they nearly drive
over a cliff, but stop just in time. *Dust / Day One* is an amalgamation of two
similar scenes, at the end of which you hear a reprise of the Cornfield Chase
music. *No Time For Caution* is probably the most tense scene, during which Cooper
has to attempt to dock their spacecraft with the main station, after the airlock
has been blown, sending them hurtling towards an alien planet’s surface. It ends
with a massive and epic chord, for which I have almost literally pulled out all
the stops.

"""